#!/bin/bash
. "${0%/*}/config"

mkdir -p "$BIN_DIRECTORY"
mkdir -p "$TMP_DIRECTORY"

program="$1"
src="$2"

installer_script=$(dirname "$0")/installer/"$program"
if [[ ! -f "$installer_script" ]]; then
    echo "unknown program: $program"
    exit 1
fi

source "$installer_script"

if [[ "$src" == "" ]]; then
    src=$(fetch_partitioner)
fi

install_partitioner "$src"

exit 0
